config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tops#index'
  resources :tops
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '札幌' },
    { id: 3, name: '千歳' },
    { id: 4, name: '函館' },
    { id: 5, name: '東北' },
    { id: 6, name: '関東' }
  ]
  include ActiveHash::Associations
  has_many :buyers
end

app/models/buyer.rb
class Buyer < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :buyer_tops
  has_many :tops, through: :buyer_tops
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :area
  belongs_to :payment
  with_options presence: true do
    validates :total_fee, numericality: true
    validates :payment_id, numericality: { only_integer: true }
    validates :area_id, numericality: { only_integer: true }
  end
end

app/models/buyer_top.rb
class BuyerTop < ApplicationRecord
  belongs_to :buyer
  belongs_to :top
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'お菓子' },
    { id: 3, name: '化粧品' },
    { id: 4, name: '海鮮' },
    { id: 5, name: '雑貨' },
    { id: 6, name: 'その他' }
  ]
  include ActiveHash::Associations
  has_many :tops
end

app/models/country.rb
class Country < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '日本' },
    { id: 3, name: 'タイ' },
    { id: 4, name: '台湾' },
    { id: 5, name: '中国' },
    { id: 6, name: '韓国' },
    { id: 7, name: 'マレーシア' },
    { id: 8, name: 'インドネシア' }
  ]
  include ActiveHash::Associations
  has_many :users
end

app/models/payment.rb
class Payment < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '現金' },
    { id: 3, name: 'クレジット' }
  ]
  include ActiveHash::Associations
  has_many :buyers
end

app/models/top.rb
class Top < ApplicationRecord
  has_one_attached :image
  has_many :buyer_tops
  has_many :buyers, through: :buyer_tops
  has_one :tops_quantity_buyer_top, -> { where(tops_quantity: true) }, class_name: 'BuyerTop'
  has_one :tops_quantity_buyer, through: :tops_quantity_buyer_top, source: :buyer
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  with_options presence: true do
    validates :items
    validates :price, numericality: { only_integer: true }
    validates :explain
    validates :category_id, numericality: { other_than: 1 }
    validates :image
  end
  validates :stock, numericality: { only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :buyers
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  VALID_PHONE_REGEX = /\A\d{10}$|^\d{11}\z/
  with_options presence: true do
    validates :nickname
    validates :phone_number, format: { with: VALID_PHONE_REGEX }
    validates :country_id, numericality: { other_than: 1 }
  end
  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'には英字と数字の両方を含めて設定してください'
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :country
end

app/models/user_payment.rb
class UserPayment
  include ActiveModel::Model
  attr_accessor :area_id, :total_fee, :payment_id, :user_id, :items, :price, :explain, :image, :category_id, :stock, :buy

  with_options presence: true do
    validates :price, numericality: true
    validates :explain
    validates :image
    validates :area_id, numericality: { only_integer: true }
  end

  def save
    # トータル価格の計算
    total_fee = 0
    buy.each do |key, value|
      price_one = Top.find(key)
      quantity_price = price_one.price * value.to_i
      total_fee += quantity_price
    end
    # 購入商品リスト
    list = []
    quantity = []
    buy.each do |key, value|
      list << key.to_i
      quantity << value.to_i
    end
    Buyer.create(area_id: area_id, payment_id: payment_id, user_id: user_id, total_fee: total_fee, image: image, top_ids: list)
    last = BuyerTop.last
    last_buyer_id = last.buyer_id
    buyerid = BuyerTop.where("buyer_id = #{last_buyer_id}")
    i = 0
    buyerid.each do |buy|
      buy.tops_quantity = quantity[i]
      buy.save
      i += 1
    end
    # 在庫数の変動
    buy.each do |key, value|
      shipment = Top.find(key)
      ship = Top.new(stock: value)
      shipment.decrement(:stock, ship.stock)
      shipment.save
    end
  end

  def save_top
    Top.create(items: items, price: price, explain: explain, image: image, category_id: category_id, stock: 0)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :phone_number, :country_id])
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
    @top = Top.all
    @tops = Top.new
    @buy = Buyer.new
    @buyer = Buyer.all.order('created_at DESC')
    @user_payment = UserPayment.new
  end

  def create
    if params[:user_payment].has_key?(:items)
      @user_payment = UserPayment.new(user_payment_params)
      @user_payment.save_top
      redirect_to root_path
    else
      @user_payment = UserPayment.new(user_payment_params)
      @user_payment.save
      redirect_to root_path
    end
  end

  def update
    if params.has_key?(:buyer)
      @buy = Buyer.find(params[:id])
      @buys = Buyer.new(check_params)
      @buy.check1 = @buys.check1
      @buy.save
      redirect_to root_path
    else
      @top = Top.find(params[:id])
      @tops = Top.new(stock_params)
      @top.increment(:stock, @tops.stock)
      @top.save
      redirect_to root_path
    end
  end

  def show
    @top = Top.find(params[:id])
  end


  private

  def stock_params
    params.require(:top).permit(:stock)
  end

  def check_params
    params.require(:buyer).permit(:check1)
  end

  def user_payment_params
    params.require(:user_payment).permit!.merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shopping</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Third party plugin JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
    <!-- Core theme JS-->
    <%# <script src="js/scripts.js"></script> %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<body>
  <!-- Header Start -->
  <header class="site-header">
    <div class="wrapper site-header__wrapper">
      <a href="#" class="brand">Brand</a>
      <nav class="nav">
        <button class="nav__toggle" aria-expanded="false" type="button">
          menu
        </button>
        <ul class="nav__wrapper">
          <li class="nav__item"><a href="#">Home</a></li>
          <li class="nav__item"><a href="#">About</a></li>
          <li class="nav__item"><a href="#">Services</a></li>
          <li class="nav__item"><a href="#">Hire us</a></li>
          <li class="nav__item"><a href="#">Contact</a></li>
        </ul>
      </nav>
    </div>
  </header>
  <!-- Header End -->

</body>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/tops/index.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Resume - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="assets/img/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
        <script src="//cdn.jsdelivr.net/npm/handsontable/dist/handsontable.full.min.js"></script>
        <link href="//cdn.jsdelivr.net/npm/handsontable/dist/handsontable.full.min.css" rel="stylesheet" type="text/css">
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <%# <link href="css/styles.css" rel="stylesheet" /> %>
    </head>

    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
            <ul>
                <% if user_signed_in?%>
                <li><%= link_to current_user.nickname, "#", class: "user-nickname" %> </li>
                <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %> </li>
                <% else %>
                <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
                <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
                <% end %>
            </ul>
            <a class="navbar-brand js-scroll-trigger" href="#page-top">
                <span class="d-none d-lg-block"><img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="assets/img/image0.png" alt="" /></span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#catalog" data-turbolinks="false">カタログ</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#purchase" data-turbolinks="false">購入画面</a></li>
                    <% if current_user.user_level == 1 %>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#education" data-turbolinks="false">新規商品登録(管理者用)</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#skills" data-turbolinks="false">商品入荷(管理者用)</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#interests" data-turbolinks="false">購入者情報</a></li>
                    <% end %>
                </ul>
            </div>
        </nav>
        <!-- Page Content-->
        <div class="container-fluid p-0">
            <!-- カタログ-->
            <section class="resume-section-a" id="catalog">
                <div class="archive">
                    <% @top.each do | product | %>
                        <li class='list'>
                            <%= link_to top_path(product.id) do %>
                            <div class='item-img-content'>
                                <%= image_tag product.image.variant(resize: '250x250'), class: "item-img" %>
                            </div>
                            <% end %>
                            <div class='item-info'>
                                <h3 class='item-name'>
                                <%= product.items %>
                                </h3>
                                <div class='item-price'>
                                <span><%= product.price %>円</span>
                                </div>
                            </div>
                            <div>
                            在庫<%= product.stock %>個
                            </div>
                            <div class="explain"><%= product.explain %></div>
                        </li>
                    <% end %>
                </div>
            </section>
            <hr class="m-0" />
            <!-- 購入画面-->
            <%= form_with model: @user_payment, url: tops_path, local: true do |f| %>
                <section class="resume-section" id="purchase">
                  <div class="archive">
                    <% i = 1 %>
                    <% @top.each do | top | %>
                        <li class='list'>
                            <div class='item-img-content'>
                                <%= image_tag top.image.variant(resize: '250x250'), class: "item-img" %>
                            </div>
                            <div class='item-info'>
                                <h3 class='item-name'>
                                <%= top.items %>
                                </h3>
                              <div class='item-price', id="item-price<%= i %>">
                              <%= top.price %>
                              </div>
                              <span>円</span>
                            </div>
                            <div>
                            在庫<%= top.stock %>個
                            <%= f.number_field :"buy[#{top.id}]", value: 0, min: 0, max: top.stock, id:"Quantity#{i}", class:"Quantity"%>個
                            </div>
                            <% i += 1 %>
                        </li>
                    <% end %>
                  </div>
                    <div>配送先</div>
                    <%= f.collection_select(:area_id, Area.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
                    <div>支払い方法</div>
                    <%= f.collection_select(:payment_id, Payment.all, :id, :name, {}, {class:"select-box", id:"itemcategory"}) %>
                            <div class="price-content">
                    <div class="price-content">
                      <span>購入金額 </span>
                      <span>
                          <span id='add-tax-price'></span>円
                      </span>
                    </div>
                    <div>
                    注文表
                    </div>
                    <%= f.file_field :image, id:"item-image" %>
                    <div class="archive">
                    <div id="example" class="handsontable"></div>
                    <%= f.submit "購入する" %>
                </section>
            <% end %>
                <hr class="m-0" />
            <% if current_user.user_level == 1 %>
            <!-- 商品入荷-->
            <%= form_with model: @user_payment, url: tops_path, local: true do |f| %>
                <section class="resume-section" id="education">
                    <div>
                        <div>
                            商品画像
                            <span>必須</span>
                        </div>
                        <div>
                            <p>
                            クリックしてファイルをアップロード
                            </p>
                            <%= f.file_field :image, id:"item-images" %>
                        </div>
                    </div>
                    <div>
                        <div>
                            商品名
                            <span >必須</span>
                        </div>
                        <%= f.text_area :items, placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
                        <div>
                            <div>
                            商品の説明
                            <span>必須</span>
                            </div>
                            <%= f.text_area :explain,placeholder:"商品の説明" ,rows:"7" ,maxlength:"1000" %>
                        </div>
                    </div>
                    <div>
                        <div>
                            <div>
                            商品の価格
                            <span>必須</span>
                            </div>
                            <%= f.text_area :price, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
                        </div>
                        <div>
                            カテゴリー
                            <span>必須</span>
                        </div>
                        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category1"}) %>
                    </div>
                    <div>
                    <%= f.submit "出品する", name:"commit1" %>
                    <%=link_to 'もどる', root_path%>
                    </div>
                </section>
            <% end %>
            <hr class="m-0" />
            <!-- 商品入荷-->
            <section class="resume-section" id="skills">
              <div class="archive">
                <% @top.each do | product | %>
                    <li class='list'>
                    <div class='item-img-content'>
                        <%= image_tag product.image.variant(resize: '250x250'), class: "item-img" %>
                    </div>
                    <div class='item-info'>
                        <h3 class='item-name'>
                        <%= product.items %>
                        </h3>
                    </div>
                    <%= form_with model: product, url: top_path(product.id), local: true do |f| %>
                      <%= f.text_field :stock, placeholder:"例）300", value: 0 %>
                      <%= f.submit "送信" %>
                    <% end %>
                <% end %>
              </div>
            </section>
            <hr class="m-0" />
            <!-- 購入者情報-->
            <section class="resume-section-a" id="interests">
                <div class="archive">
                    <% @buyer.each do | product | %>
                        <li class='list'>
                            <% if product.image.attached? %>
                            <div class='item-img-content'>
                            <%= image_tag product.image.variant(resize: '250x250'), class: "item-img" %>
                            </div>
                            <% end %>
                            <div class='item-info'>
                                <div class='item-name'>
                                <%= l product.created_at %>
                                </div>
                                <div class='item-name'>
                                <%= product.area.name %>
                                </div>
                                <div class='item-name'>
                                <%= product.total_fee %>円
                                </div>
                                <div class='item-price'>
                                <span><%= product.payment.name %></span>
                                </div>
                            </div>
                            <h3>
                            <%= product.user.nickname %>様
                            </h3>
                            <div class="explain">
                            <% current_id = product.id %>
                            <% purchase_list = BuyerTop.where("buyer_id = #{current_id}") %>
                                <% purchase_list.each do | buy | %>
                                <% purchase_object = Top.find(buy.top_id) %>
                                <% if buy.tops_quantity != 0 %>
                                <div>
                                <%= purchase_object.items %>、<%= buy.tops_quantity %>個
                                </div>
                                <% end %>
                                <% end %>
                            </div>
                            <% if product.check1 == 1 %>
                                <h6>配送完了済み<h6>
                            <% else %>
                                <div class="explain">
                                <%= form_with model: product, url: top_path(product.id), local: true do |f| %>
                                配送が完了後チェック<%= f.check_box :check1, {class: "check_box"} %>
                                <%= f.submit "送信" %>
                                </div>
                                <% end %>
                            <% end %>
                        </li>
                    <% end %>
                </div>
            </section>
            <% end %>
        </div>
        <!-- Bootstrap core JS-->

    </body>
</html>

app/views/tops/show.html.erb
<li class='list'>
    <div class='item-img-content'>
        <%= image_tag @top.image.variant(resize: '250x250'), class: "item-img" %>
    </div>
    <div class='item-info'>
        <h3 class='item-name'>
        <%= @top.items %>
        </h3>
        <div class='item-price'>
        <span><%= @top.price %>円</span>
        </div>
    </div>
    <div>
    在庫<%= @top.stock %>個
    </div>
    <div class="explain"><%= @top.explain %></div>
</li>